/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GTokenRouteImport } from './routes/g.$token'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as AuthenticatedVectorizeRouteImport } from './routes/_authenticated/vectorize'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedHalftoneRouteImport } from './routes/_authenticated/halftone'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedEditorRouteImport } from './routes/_authenticated/editor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCropRouteImport } from './routes/_authenticated/crop'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedBackgroundRouteImport } from './routes/_authenticated/background'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GTokenRoute = GTokenRouteImport.update({
  id: '/g/$token',
  path: '/g/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVectorizeRoute = AuthenticatedVectorizeRouteImport.update({
  id: '/vectorize',
  path: '/vectorize',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHalftoneRoute = AuthenticatedHalftoneRouteImport.update({
  id: '/halftone',
  path: '/halftone',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditorRoute = AuthenticatedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCropRoute = AuthenticatedCropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackgroundRoute = AuthenticatedBackgroundRouteImport.update({
  id: '/background',
  path: '/background',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/background': typeof AuthenticatedBackgroundRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/chat': typeof AuthenticatedChatRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/crop': typeof AuthenticatedCropRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/editor': typeof AuthenticatedEditorRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/halftone': typeof AuthenticatedHalftoneRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vectorize': typeof AuthenticatedVectorizeRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/g/$token': typeof GTokenRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/background': typeof AuthenticatedBackgroundRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/chat': typeof AuthenticatedChatRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/crop': typeof AuthenticatedCropRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/editor': typeof AuthenticatedEditorRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/halftone': typeof AuthenticatedHalftoneRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vectorize': typeof AuthenticatedVectorizeRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/g/$token': typeof GTokenRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/background': typeof AuthenticatedBackgroundRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/crop': typeof AuthenticatedCropRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/editor': typeof AuthenticatedEditorRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/halftone': typeof AuthenticatedHalftoneRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/vectorize': typeof AuthenticatedVectorizeRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/g/$token': typeof GTokenRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/background'
    | '/backups'
    | '/catalog'
    | '/chat'
    | '/clients'
    | '/crop'
    | '/dashboard'
    | '/editor'
    | '/employees'
    | '/gallery'
    | '/generate'
    | '/halftone'
    | '/orders'
    | '/portfolio'
    | '/projects'
    | '/quality'
    | '/settings'
    | '/vectorize'
    | '/api/generate-image'
    | '/g/$token'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/background'
    | '/backups'
    | '/catalog'
    | '/chat'
    | '/clients'
    | '/crop'
    | '/dashboard'
    | '/editor'
    | '/employees'
    | '/gallery'
    | '/generate'
    | '/halftone'
    | '/orders'
    | '/portfolio'
    | '/projects'
    | '/quality'
    | '/settings'
    | '/vectorize'
    | '/api/generate-image'
    | '/g/$token'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/background'
    | '/_authenticated/backups'
    | '/_authenticated/catalog'
    | '/_authenticated/chat'
    | '/_authenticated/clients'
    | '/_authenticated/crop'
    | '/_authenticated/dashboard'
    | '/_authenticated/editor'
    | '/_authenticated/employees'
    | '/_authenticated/gallery'
    | '/_authenticated/generate'
    | '/_authenticated/halftone'
    | '/_authenticated/orders'
    | '/_authenticated/portfolio'
    | '/_authenticated/projects'
    | '/_authenticated/quality'
    | '/_authenticated/settings'
    | '/_authenticated/vectorize'
    | '/api/generate-image'
    | '/g/$token'
    | '/_authenticated/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  GTokenRoute: typeof GTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$token': {
      id: '/g/$token'
      path: '/g/$token'
      fullPath: '/g/$token'
      preLoaderRoute: typeof GTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vectorize': {
      id: '/_authenticated/vectorize'
      path: '/vectorize'
      fullPath: '/vectorize'
      preLoaderRoute: typeof AuthenticatedVectorizeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/halftone': {
      id: '/_authenticated/halftone'
      path: '/halftone'
      fullPath: '/halftone'
      preLoaderRoute: typeof AuthenticatedHalftoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editor': {
      id: '/_authenticated/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthenticatedEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crop': {
      id: '/_authenticated/crop'
      path: '/crop'
      fullPath: '/crop'
      preLoaderRoute: typeof AuthenticatedCropRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/background': {
      id: '/_authenticated/background'
      path: '/background'
      fullPath: '/background'
      preLoaderRoute: typeof AuthenticatedBackgroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBackgroundRoute: typeof AuthenticatedBackgroundRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCropRoute: typeof AuthenticatedCropRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEditorRoute: typeof AuthenticatedEditorRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedHalftoneRoute: typeof AuthenticatedHalftoneRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVectorizeRoute: typeof AuthenticatedVectorizeRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBackgroundRoute: AuthenticatedBackgroundRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCropRoute: AuthenticatedCropRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEditorRoute: AuthenticatedEditorRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedHalftoneRoute: AuthenticatedHalftoneRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVectorizeRoute: AuthenticatedVectorizeRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  GTokenRoute: GTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
